import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import SideBar from '@/app/[locale]/(admin)/components/sidebar';
import '@/app/globals.css';
import Provider from '@/utils/Provider';

const poppins = Poppins({
	weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Admin barber shop',
	description: 'Generated by Admin barber shop',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<Provider>
					<SideBar>
						<div className='bg-gray-900 text-gray-200'>{children}</div>
					</SideBar>
				</Provider>
			</body>
		</html>
	);
}
